# Generated by Django 2.2.9 on 2020-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contactos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='interacciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pedidos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_local',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
