# Generated by Django 2.2.9 on 2020-01-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_auto_20200113_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='cliente',
            new_name='establecimiento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contactos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.Contacto'),
        ),
    ]
