# Generated by Django 2.2.9 on 2020-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_auto_20200113_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contactos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contactos',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Contacto'),
        ),
    ]
