# Generated by Django 2.2.9 on 2020-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_auto_20200113_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contactos',
            field=models.ManyToManyField(blank=True, null=True, related_name='establecimientos', to='gestor.Contacto'),
        ),
    ]
