# Generated by Django 2.2.9 on 2020-01-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_auto_20200113_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contactos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='gestor.Cliente'),
        ),
    ]
