# Generated by Django 2.2.9 on 2020-01-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0013_remove_producto_presentaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='pedidos',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='gestor.Cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='gestor.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Items_Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.Coleccion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestor.Pedido')),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.Presentacion')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.Producto')),
            ],
        ),
    ]
